---
jenkins_connection_delay: 8
jenkins_connection_retries: 10
jenkins_hostname: localhost

jenkins_dest: /opt/jenkins
jenkins_jar_location: "{{ jenkins_dest }}/jenkins-cli.jar"
jenkins_updates_file: "{{ jenkins_dest }}/updates.json"

plugins:
  - 'credentials'
  - 'external-monitor-job'
  - 'git-client'
  - 'htmlpublisher'
  - 'mailer'
  - 'matrix-auth'
  - 'matrix-project'
  - 'publish-over-ssh'
  - 'role-strategy'
  - 'ssh-credentials'
  - 'ssh-agent'
  - 'git'
  - 'ansible'
  - 'gitlab-merge-request-jenkins'